### ISSUE TITLE
scrub task will fail on mixed mode filesystems

### ISSUE THREAD

**Issue by ian-kelling** [kdave/btrfsmaintenance#16]
I have btrfs on /boot, it's 2.4 gigs, btrfs.mkfs set it to mixed mode by default. btrfs-balance.sh runs this:

    btrfs balance start -dusage=0 /boot

Which fails, tells me to look at syslog or dmesg, syslog says:

    kernel: BTRFS error (device sda3): with mixed groups data and metadata balance options must be the same

Tried this instead which worked:

    btrfs balance start -dusage=0 -musage=0 /boot

**Comment by kdave** [comment]
The mixed mode hasn't been considered but should not be hard to add, we just have to detect it and supply the right options to balance.

**Comment by kdave** [comment]
Can you please test the fix in branch balance-mixed-bg?

**Comment by ian-kelling** [comment]
I've tested it. It works. I've reviewed the code, it looks good. Feel free to merge it and close this.

**Comment by kdave** [comment]
Thanks!
