### ISSUE TITLE
unexpected operator with dash

### ISSUE THREAD

**Issue by Micha-Btz** [kdave/btrfsmaintenance#23]
hi there,

I have setup the config  with:

>  BTRFS_BALANCE_MOUNTPOINTS="/mnt/btrfs/root:/mnt/btrfs/media:/mnt/backup"

for balance and for scrub and if i run the scripts, there are the following error message:

> /etc/cron.monthly//btrfs-scrub: 14: [: /mnt/btrfs/root:/mnt/btrfs/media:/mnt/backup: unexpected operator
> /etc/cron.weekly//btrfs-balance: 14: [: /mnt/btrfs/root:/mnt/btrfs/media:/mnt/backup: unexpected operator
> 
I'm using Debian Sid:

> ll /bin/sh
> lrwxrwxrwx 1 root root 4 Jan 24 06:16 /bin/sh -> dash
> dpkg -l|grep dash
> ii  dash                                                        0.5.8-2.4                            amd64        POSIX-compliant shell
> 

All scripts run successfully on the mount points. If I run the script with bash there is no error maybe point /bin/sh to /bin/bash?
I will add an additional question to trim. I don't  use the fstrim timer for systemd. 
But there are a lot of information in the net and the most are quite old. Should i run trim on a luks encrypted volume with btrfs on a ssd? As far as i understand the wiki from btrfs this is not needed because the filesystem itself take care of it.

thanks Micha

**Comment by kdave** [comment]
This looks like some mixup. /bin/dash understands [ and -f operators, from what you quoted it looks like the contents of the file `/etc/cron.monthly//btrfs-scrub` is interpreted and the `:` confuse the shell. The scripts use the `.sh` extension so please check whether you have the same files in your cron directory as are in the git.

**Comment by kdave** [comment]
Regarding the trim question: it's not necessary to run the trim on a SSD (this used to be sort of required for older types that did not do the internal block reordering and garbage collection, otherwise this led to decreased performance). With LUKS it has some security implications (like revealing which disk areas are live and free), this is up to you to decide whether this applies in your case. This also needs an extra cryptsetup option to actually allow to pass the TRIM command to the level below LUKS.
The filesystem does not do trim by default, must be either the fstrim command (or ioctl directly) or mounted with `-o discard` (with performance implications). HTH

**Comment by Micha-Btz** [comment]
hm,

I changed the confug an let the btrfsmaintenance-refresh-cron.sh create the symlinks.

> cron.monthly:
> insgesamt 28
> drwxr-xr-x 1 root root  150 Jan 29 19:13 .
> drwxr-xr-x 1 root root 5636 Jan 27 16:39 ..
> -rwxr-xr-x 1 root root  127 Dez 30 10:13 01backup_nachricht
> -rwxr-xr-x 1 root root  464 Jan 15 19:26 01btrbk
> -rwxr-xr-x 1 root root  313 Dez 19 16:49 0anacron
> lrwxrwxrwx 1 root root   43 Jan 29 19:13 btrfs-defrag -> /usr/share/btrfsmaintenance/btrfs-defrag.sh
> lrwxrwxrwx 1 root root   42 Jan 29 19:13 btrfs-scrub -> /usr/share/btrfsmaintenance/btrfs-scrub.sh
> -rwxr-xr-x 1 root root  534 Dez 19 16:49 debsums
> -rw-r--r-- 1 root root  102 Dez 19 16:49 .placeholder
> 
> cron.weekly:
> insgesamt 28
> drwxr-xr-x 1 root root  134 Jan 29 19:13 .
> drwxr-xr-x 1 root root 5636 Jan 27 16:39 ..
> -rwxr-xr-x 1 root root  362 Jan 18 21:15 01btrbk
> -rwxr-xr-x 1 root root  312 Dez 19 16:49 0anacron
> lrwxrwxrwx 1 root root   44 Jan 29 19:13 btrfs-balance -> /usr/share/btrfsmaintenance/btrfs-balance.sh
> -rwxr-xr-x 1 root root  533 Dez 19 16:49 debsums
> -rwxr-xr-x 1 root root  723 Dez 19 16:49 man-db

Now I'm a little confused. The colon : in the conf is correct?
