### ISSUE TITLE
ebuild for gentoo

### ISSUE THREAD

**Issue by samuelbernardo** [kdave/btrfsmaintenance#31]
Very nice work for missing tools for btrfs.
Although you already created a rpm spec file, it would be usefull an ebuild to install in gentoo.
In arch there is already an aur version that I'll adapt into a gentoo ebuild:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=btrfsmaintenance

I'll fork your repository and then do a pull request if needed for any required patch.

Thanks for sharing your awesome project!

**Comment by kdave** [comment]
No problem adding an ebuild script.

**Comment by madmartin** [comment]
It does not make sense to add an ebuild file into the source package. There is already a new-package bug open: https://bugs.gentoo.org/show_bug.cgi?id=595762
The right way to add an ebuild to gentoo is to fork https://github.com/gentoo/gentoo and add the ebuild there.
If I have time I will do this.

**Comment by samuelbernardo** [comment]
Hello @madmartin ,

I already created the ebuild and published in my overlay:
https://github.com/samuelbernardo/ssnb-overlay/tree/9ca9fec3fe7d8bab961fdbf8fe8a45c803b1449b/sys-fs/btrfsmaintenance

It's tested and working in my workstation.
I'll be glad to have your improvement.

Thanks

**Comment by kdave** [comment]
AFAICS this has been solved outside of this project, closing.
