### ISSUE TITLE
defrag does not descend into subvolumes

### ISSUE THREAD

**Issue by Zugschlus** [kdave/btrfsmaintenance#37]
Hi,
btrfs-defrag.sh makes use of find -xdev, which treats a subvolume boundary as device boundary and stops descending. If this is the intended behavior, it should be documented.
If it is not the intendedn behavior, the script needs to build a list of subvolumes that are part oft the BTRFS_DEFRAG_PATHS and invoke find for each of them.
Greetings
Marc

**Comment by kdave** [comment]
Can you please check if the updated documentation is sufficient? Thanks.
