### ISSUE TITLE
Call /bin/bash instead of /bin/sh

### ISSUE THREAD

**Issue by jph76** [kdave/btrfsmaintenance#49]
btrfs-balance etc. call /bin/sh, therefore, [ "$FS" == "btrfs" ] in btrfsmaintenance-functions line 76 will not work.

Fix: call /bin/bash

**Comment by eku** [comment]
```[ "$FS" = "btrfs" ]``` works with standard shell.

**Comment by jph76** [comment]
On Debian, standard shell `/bin/sh` is dash where `[ "$FS" = "btrfs" ]` won’t work.

**Comment by eku** [comment]
@jph76  AFAIK dash is POSIX compliant and the above mentioned way to compare strings is the POSIX way. See also https://wiki.ubuntu.com/DashAsBinSh

**Comment by kdave** [comment]
The `=` is already used in several places so if you haven't observed any problems, I assume it works under dash too. There are no advanced shell tricks used so `sh` should be sufficient.

**Comment by jph76** [comment]
Now it works like a charm. Thanks!
