### ISSUE TITLE
BTRFS_VERBOSITY missing

### ISSUE THREAD

**Issue by billimek** [kdave/btrfsmaintenance#5]
In btrfs-defrag.sh there is a reference to $BTRFS_VERBOSITY in the execution of the find command.

Specifically,

`find "$P" -size "$BTRFS_DEFRAG_MIN_SIZE" -type f -xdev \
-exec /sbin/btrfs filesystem defrag -t 32m -f "$BTRFS_VERBOSITY" '{}' \;`

This causes an execution error as the `"$BTRFS_VERBOSITY"` gets translated as `""` which causes an error with find (at least find v4.4.2)

**Comment by kdave** [comment]
The variable hasn't appeared in git AFAICS, though I see it in preliminary versions of the tool so there are users, it got lost from the sysconfig template. I'll remove the qutoes for now and look if we want the variable.
