### ISSUE TITLE
dist-install.sh > TimerUnits

### ISSUE THREAD

**Issue by SManAT** [kdave/btrfsmaintenance#58]
Hi!
First: tx for the good work.
Second:
Implement in dist-install.sh the Log Message, somthing like:
"Now copy the Service.Units and Timer.Units to /etc/systemd/system and do a btrfsmaintenance-refresh-cron.sh timer"

**Comment by kdave** [comment]
Thanks for the suggestion, the following text has been committed. The script installs only the cron scripts as the path is known, I'm not sure about the timer units so there's just the message and the decision is left to the distro packagers.

```
Installation path: 
For cron-based setups:
- edit cron periods and mount points in /btrfsmaintenance
- run ./btrfsmaintenance-refresh-cron.sh to update cron symlinks

For systemd.timer-based setups:
- copy *.timer files to the systemd.unit path (eg. /usr/lib/systemd/system/ or /etc/systemd/system)
- run './btrfsmaintenance-refresh-cron.sh timer' to enable and schedule the timers
```
