### ISSUE TITLE
Hard-coded path for fstrim breaks in ubuntu

### ISSUE THREAD

**Issue by billimek** [kdave/btrfsmaintenance#6]
In btrfs-trim.sh there is a hard-coded path reference to `/usr/sbin/fstrim`.  In at least ubuntu distributions fstrim is installed by default to `/sbin`.

Recommend removing hard-coded paths to commands.

**Comment by kdave** [comment]
Agreed, the scripts enforce PATH order and contents, no point to hardcode the path.
