### ISSUE TITLE
Question: Why different default musage/dusage defaults?

### ISSUE THREAD

**Issue by billdenney** [kdave/btrfsmaintenance#64]
First, thanks for these scripts!  I'd cobbled something together that didn't work nearly as well.

Why do the default values for dusage and musage not match?  I would have assumed that making them both the same would yield optimal balancing, but musage only goes to 30 while dusage goes to 50.

https://github.com/kdave/btrfsmaintenance/blob/cf421fcadbbad9665ce3d14cba7d673d9386346d/sysconfig.btrfsmaintenance#L53-L74

**Comment by sten0** [comment]
@billdenney IIRC this is because 30 is the cut-point of diminishing returns for balancing metadata, where 50 is the cut-point for data.

**Comment by billdenney** [comment]
Thanks for the explanation!

**Comment by kdave** [comment]
In version 0.5 the defaults have been reduced, the explanation is in the readme. Closing.
