### ISSUE TITLE
Feature Request for more versatile periods

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfsmaintenance#65]
I wish to have the scrub run on the 1st Saturday of the month at 9am. Midnight doesn't make much sense for me (I'll likely shut down the PC before it has a chance to finish), nor does just doing it on whatever happens to be the first day.

I set BTRFS_SCRUB_PERIOD="Saturday *-*-1..7 9:00" in the config, but the next run is on midnight on the 1st. After this run it will be on the first Saturday on the month @ 9:00. So it runs twice a month.

I realise that the valid options are 'Type: string(none,daily,weekly,monthly)', so probably not a bug, but a feature request to support the full set of https://jlk.fjfi.cvut.cz/arch/manpages/man/systemd.time.7#CALENDAR_EVENTS

**Comment by adrfantini** [comment]
I would also like this feature to be implemented: I have a small server running in the same room where I sleep, so I do not want disks to spin up during the night. Currently, scrubs are performed monthly at 10:00AM: can I replicate something like this using `btrfsmaintenance`.

**Comment by kdave** [comment]
Thanks for the suggestion. The documented periods originated from the cron setups that pre-created the daily/weekly/monthly periods as the most common. When the systemd timer support was added, the periods were copied, but in fact the rich format of calendar events is already supported.
This will be better documented.

**Comment by adrfantini** [comment]
You mean that I could already set a systemd calendar string as periodicity and it would work?

**Comment by CorrosiveTruths** [comment]
Oh cool.

I'll file a separate bug about the double-running behaviour then.

(I'm guessing because it uses the /etc/systemd/system/btrfs-trim.timer.d/schedule.conf drop-in, but also the /lib/systemd/system/btrfs-trim.timer which contains 'monthly' but I'd like to prove that to myself first)

**Comment by CorrosiveTruths** [comment]
See #71

**Comment by CorrosiveTruths** [comment]
Re-opened, just realised you're tracking this issue for 0.5

**Comment by kdave** [comment]
The patches adding documentation (and some validation) have been merged.
