### ISSUE TITLE
"echo -n" bashism in /bin/sh scripts

### ISSUE THREAD

**Issue by automorphism88** [kdave/btrfsmaintenance#74]
The scripts use `echo -n` to parse the colon-separated paths in the config file. This is a problem if `/bin/sh` is dash, since `-n` is taken as part of the string to be echoed and not as an option, and ends up getting prepended to the first path in the list.

As a solution, either the more portable `printf` should be used in place of `echo`, or the shebangs should be changed from `/bin/sh` to `/bin/bash`.

**Comment by eku** [comment]
@automorphism88  BTW ```#!/usr/bin/env bash``` would be the correct way.

**Comment by automorphism88** [comment]
> @automorphism88 BTW `#!/usr/bin/env bash` would be the correct way.

Not necessarily. That approach has both advantages and disadvantages, and if you wanted to use `/usr/bin/env`, then it might as well be `#!/usr/bin/env sh` right now, but it isn't.

**Comment by kdave** [comment]
All scripts have been switched to `#!/bin/bash`. I've run `checkbashisms -n -p` to see how many there are, enough to do a simple fix instead for now. All fixable though.
